apiVersion: apps/v1
kind: Deployment
metadata:
  name: generatexmlfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generatexmlfiles
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
